---
title: "p8105_hw6_cd3591"
author: "Anny"
date: "2025-11-28"
output: github_document
---

```{r}
# set up libraries
library(tidyverse)
```

# Problem 1
```{r}
# import the dataset
homicides_raw = read_csv("homicide-data.csv") %>% 
  janitor::clean_names()

# tidy the dataset
homicides = homicides_raw %>%
  mutate(
    city_state = str_c(city, ", ", state),  # e.g. “Baltimore, MD”
    resolved = ifelse(disposition == "Closed by arrest", 1, 0),  # 1 means homicide is solved, 0 means it is not (binary)
    victim_age = as.numeric(victim_age)  # Be sure that victim_age is numeric
  ) %>%
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"),  
    # Omit cities Dallas, TX; Phoenix, AZ; and Kansas City, MO, Tulsa, AL
    victim_race %in% c("White", "Black"),  # limit your analysis those for whom victim_race is white or black
    !is.na(victim_age)
  ) %>%
  mutate(
    victim_sex = relevel(factor(victim_sex), ref = "Female"),  # make the reference level is female in victim_sex
    victim_race = relevel(factor(victim_race), ref = "White")  # make the reference level is white in victim_race
  )
```

```{r}
# Baltimore only: OR + CI for male vs female
baltimore_fit = homicides %>%
  filter(city_state == "Baltimore, MD") %>%
  glm(resolved ~ victim_age + victim_sex + victim_race, data = ., family = binomial())

baltimore_or =
  broom::tidy(baltimore_fit, exponentiate = TRUE, conf.int = TRUE) %>%
  filter(term == "victim_sexMale") %>%
  select(estimate, conf.low, conf.high)

baltimore_or
```

The estimate of the ajusted OR is `r baltimore_or[1]`, with the confidence interval of (`r baltimore_or[2]`, `r baltimore_or[3]`).